[peripherals][u8g2] Add official support
RT-Thread/packages pull request #1030
Opened 2021-09-06 12:58 UTC by wuhanstudio

u8g2 对 RT-Thread 的支持已经完全 upstream  了：

https://github.com/olikraus/u8g2/pull/1547
https://github.com/olikraus/u8g2/pull/1550

- 添加 official (upstream) 的仓库
- official (upstream) 同时支持 C/C++，所以不需要单独维护 C latest 和 C++ latest 了

2021-09-06 17:36 UTC, mysterywolf requested changes

2021-09-06 17:36 UTC, mysterywolf commented on peripherals/u8g2/package.json
> +      "URL": "https://github.com/olikraus/u8g2.git",
这个URL必须要和上面的一致否则会导致gitee备份不过去，去年吃过这个亏。可以单独开一个软件包当做官方的。
不可以上面是你的github 下面是官方的github

2021-09-06 19:54 UTC, wuhanstudio commented on peripherals/u8g2/package.json
> +      "URL": "https://github.com/olikraus/u8g2.git",
原来是 giee 备份的问题，是说 RTT Studio 里用不同仓库是可以正常切换的

2021-09-06 20:03 UTC, mysterywolf commented on peripherals/u8g2/package.json
> +      "URL": "https://github.com/olikraus/u8g2.git",
是的 如果是在海外 这么写没有问题，主要是gitee备份不过去，中国地区没法用。

2021-09-06 20:48 UTC, mysterywolf commented
可以像entertainment一样，内置一个子目录，子目录里含着你的仓库和官方的仓库 两个软件包。这样归类比较清晰。

2021-09-06 21:11 UTC, wuhanstudio commented
现在主要是国内/海外用户怎么平衡：

1. 国内多仓库 gitee 无法同步 (可以多个仓库放在同一目录解决)
2. 现在 RTT 国内用户居多，但是 u8g2，rosserial，micro_ros 一些中文文档不方便 upstream
3. 海外的 upstream 仓库维护者不太了解 RT-Thread，如果 upstream 要修 RTT 相关的 bug 周期就会非常长，所以之前考虑保留自己维护的版本和 upsream 版本，定期从 upstream 合并

(其实如果海外 upstream  熟悉 RT-Thread 的开发者越来越多，我就可以直接删库跑路了，把后续的维护交给 upstream)

2021-09-07 01:12 UTC, mysterywolf commented
> 可以像entertainment一样，内置一个子目录，子目录里含着你的仓库和官方的仓库 两个软件包。这样归类比较清晰。

要不然就先这么处理，新建一个u8g2-offical软件包，现在的u8g2也不删，然后看一下u8g2上游作者的态度，如果合并比较速度的话，就可以删库跑路了。🤣

2021-09-29 02:14 UTC, closed without merging