[fix] 在没有释出版本之前，ota_downloader 的最新代码应该匹配 webclient 的最新代码，因为引用了 webclient 中最新实现的一个函数。
RT-Thread/packages pull request #1080
Opened 2021-11-15 10:51 UTC by xiangxistu

you should choose the laster of "webclient" when you choose the laster of "ota_downloader".

https://github.com/RT-Thread-packages/webclient/pull/76

2021-11-15 10:58 UTC, Guozhanxin approved these changes

2021-11-15 15:12 UTC, mysterywolf requested changes

2021-11-15 15:12 UTC, mysterywolf commented on iot/webclient/Kconfig
> +        default PKG_USING_WEBCLIENT_LATEST_VERSION if PKG_USING_OTA_DOWNLOADER_LATEST_VERSION
这个地方别改了 咱俩冲突了，我直接改成默认是最新版的

2021-11-16 02:38 UTC, Guozhanxin commented on iot/webclient/Kconfig
> +        default PKG_USING_WEBCLIENT_LATEST_VERSION if PKG_USING_OTA_DOWNLOADER_LATEST_VERSION
别默认最新版啊

2021-11-16 02:48 UTC, mysterywolf commented on iot/webclient/Kconfig
> +        default PKG_USING_WEBCLIENT_LATEST_VERSION if PKG_USING_OTA_DOWNLOADER_LATEST_VERSION
现在是发布版最容易出问题，因为rtt官方100来个软件包，rtt官方无暇照料，很多软件包发布的版本都停留在一年之前，很多问题明明都提pr解决了，然后就是因为默认还是使用发布版，结果用户还在用户抱怨。

2021-11-18 08:48 UTC, Guozhanxin commented on iot/webclient/Kconfig
> +        default PKG_USING_WEBCLIENT_LATEST_VERSION if PKG_USING_OTA_DOWNLOADER_LATEST_VERSION
发布版有问题，那就解决问题啊，不能因为有的发布版有问题，就都默认使用最新版了，这样更容易出问题了啊。

2021-11-18 08:49 UTC, Guozhanxin commented on iot/webclient/Kconfig
> +        default PKG_USING_WEBCLIENT_LATEST_VERSION if PKG_USING_OTA_DOWNLOADER_LATEST_VERSION
等满老师睡醒，我没发群里让大家一起看看吧

2021-12-08 06:22 UTC, Guozhanxin commented
我先把这个合并了，后面有必要的话再改。

2021-12-08 06:22 UTC, merged