添加软件包PainterEngine和PainterEngine_AUX
RT-Thread/packages pull request #1086
Opened 2021-11-23 06:31 UTC by QPLover

2021-11-25 02:57 UTC, Guozhanxin commented
厉害了👍，在RTT上运行起来是什么效果呢，有演示效果吗？

2021-11-25 03:02 UTC, mysterywolf requested changes

2021-11-25 03:02 UTC, mysterywolf commented on multimedia/PainterEngine/PainterEngine_AUX/Kconfig
> +    bool
666 刚刚探索辅助软件包新招呼就学会用了，经过实践 这个bool后面要写东西 否则在studio上会出问题，参见这里https://github.com/RT-Thread/packages/blob/master/system/CMSIS/CMSIS_5_AUX/Kconfig#L4

2021-11-25 03:06 UTC, mysterywolf commented
另外，辅助软件包这种方法一般是迫不得已才使用的，一般是遇到了一些阻力，否则应该尝试和原作者沟通，看看能不能在他的仓库里直接驻留rtt的移植代码，我注意到他的仓库里是给其他操作系统留出了一个文件夹的 https://github.com/matrixcascade/PainterEngine/tree/master/platform ，可以创建一个RT-Thread文件夹，然后把rtt的Sconscript以及必要的移植文件放在RT-Thread文件夹里。此外需要在根目录添加一个Sconscript脚本引导到RT-Thread文件夹的Sconscript脚本中，参见：https://github.com/olikraus/u8g2/blob/master/SConscript。

2021-11-25 14:39 UTC, QPLover commented
@Guozhanxin 这里有一个我录制的[演示视频](https://www.bilibili.com/video/BV1Jr4y1y7ZT)，视频里我演示的是PainterEngine的Live2D功能，这也是我最中意PainterEngine的一点

2021-11-25 14:42 UTC, QPLover commented
> 厉害了👍，在RTT上运行起来是什么效果呢，有演示效果吗？

这里有一个我录制的[演示视频](https://www.bilibili.com/video/BV1Jr4y1y7ZT)，视频里我演示的是PainterEngine的Live2D功能，这也是我最中意PainterEngine的一点

2021-11-25 15:26 UTC, QPLover commented on multimedia/PainterEngine/PainterEngine_AUX/Kconfig
> +    bool
这里我刚刚修改了

2021-11-25 15:27 UTC, QPLover commented on multimedia/PainterEngine/PainterEngine_AUX/Kconfig
> +    bool
OK，这里我已经修改了

2021-11-25 15:43 UTC, QPLover commented
> 另外，辅助软件包这种方法一般是迫不得已才使用的，一般是遇到了一些阻力，否则应该尝试和原作者沟通，看看能不能在他的仓库里直接驻留rtt的移植代码，我注意到他的仓库里是给其他操作系统留出了一个文件夹的 https://github.com/matrixcascade/PainterEngine/tree/master/platform ，可以和原作者联系一下，给他的仓库提交一个pr，创建一个RT-Thread文件夹，然后把rtt的Sconscript以及必要的移植文件放在RT-Thread文件夹里。此外需要在根目录添加一个Sconscript脚本引导到RT-Thread文件夹的Sconscript脚本中，参见：https://github.com/olikraus/u8g2/blob/master/SConscript https://github.com/olikraus/u8g2/tree/master/sys/rt-thread

@mysterywolf 我刚刚往PainterEngine的作者的存储库里提交了在根目录添加Sconscript的PR，但作者不接受在根目录里添加构建脚本的做法，所以我目前只能使用辅助软件包

2021-11-25 17:54 UTC, mysterywolf commented
先等一下 pr刚提上去，作者还没有反馈

2021-11-26 08:54 UTC, QPLover commented
> 先等一下 pr刚提上去，作者还没有反馈

@mysterywolf 我用QQ联系了作者，作者说他不接受在根目录里添加构建脚本的做法

2021-11-28 06:38 UTC, mysterywolf approved these changes

2021-11-28 23:24 UTC, merged