【提交】基于终端显示的跑酷游戏
RT-Thread/packages pull request #1087
Opened 2021-11-23 06:39 UTC by ZhuTuMengJin

2021-11-23 10:33 UTC, mysterywolf requested changes

2021-11-23 10:33 UTC, mysterywolf commented on misc/entertainment/parkour/package.json
> +  "repository": "https://github.com/ZhuTuMengJin/Myhub",
请确认这个仓库地址的有效性

2021-11-25 03:01 UTC, Guozhanxin commented on misc/entertainment/parkour/package.json
> +  "repository": "https://github.com/ZhuTuMengJin/Myhub",
或者这个仓库是不是私有的，没有开放？

2021-12-08 06:20 UTC, Guozhanxin commented
先关闭此pr，后面有更新再重新提交吧

2021-12-08 06:20 UTC, closed without merging