添加CW2015锂电池电量计驱动软件包
RT-Thread/packages pull request #1127
Opened 2021-12-20 12:16 UTC by qingehao

2021-12-20 12:29 UTC, balanceTWK commented
请问下，要用你的软件包，电池的建模信息，怎么来的？

2021-12-20 17:06 UTC, mysterywolf requested changes

2021-12-20 17:06 UTC, mysterywolf commented on peripherals/cw2015/package.json
> +      "VER_SHA": "main"
这个地方不是main 是master 你的仓库里没有main分支

2021-12-21 07:03 UTC, qingehao commented
> 请问下，要用你的软件包，电池的建模信息，怎么来的？

建模信息需要将自己所用型号电池送至赛微微电子公司进行测试建模，精确的建模信息还需要PCB板连同电池一同送至，不精确的情况下，使用一些现成型号电池的建模信息。

2021-12-21 07:03 UTC, qingehao commented on peripherals/cw2015/package.json
> +      "VER_SHA": "main"
已修改

2021-12-21 08:04 UTC, balanceTWK commented
> > 请问下，要用你的软件包，电池的建模信息，怎么来的？
> 
> 建模信息需要将自己所用型号电池送至赛微微电子公司进行测试建模，精确的建模信息还需要PCB板连同电池一同送至，不精确的情况下，使用一些现成型号电池的建模信息。

好吧，原厂竟然不把建模的方法开放出来。。。使用门槛++

2021-12-28 01:20 UTC, Guozhanxin commented on peripherals/cw2015/package.json
> +      "URL": "https://codeload.github.com/qingehao/CW2015/zip/refs/tags/v1.0.0",
请把这个链接换成 `https://github.com/qingehao/CW2015/archive/refs/tags/v1.0.0.zip`

2022-01-07 03:23 UTC, merged