add:LuatOS-SOC packages
RT-Thread/packages pull request #1129
Opened 2021-12-22 08:39 UTC by Dozingfiretruck

add:LuatOS-SOC packages 
LuatOS : https://gitee.com/openLuat/LuatOS

2021-12-22 14:52 UTC, mysterywolf requested changes

2021-12-22 14:52 UTC, mysterywolf commented on system/LuatOS_SOC/package.json
> +  "repository": "https://gitee.com/openLuat/luatos-soc-rtt",
请使用github仓库

2021-12-22 14:53 UTC, mysterywolf commented on system/LuatOS_SOC/package.json
> +  "repository": "https://gitee.com/openLuat/luatos-soc-rtt",
gitee有机器人侦测系统

2021-12-22 14:54 UTC, mysterywolf commented
而且，https://gitee.com/openLuat/LuatOS 这仓库里貌似也没有Sconscript脚本

2021-12-22 14:57 UTC, Dozingfiretruck commented
> https://gitee.com/openLuat/LuatOS

https://gitee.com/openLuat/LuatOS是主库，https://gitee.com/openLuat/luatos-soc-rtt是做成的软件包

2021-12-22 14:59 UTC, mysterywolf commented
噢噢 好 有Sconscript就可以的，但是要托管在github上

2021-12-22 15:00 UTC, Dozingfiretruck commented
> 噢噢 好 有Sconscript就可以的，但是要托管在github上

好的呢，我改一下

2021-12-22 15:01 UTC, wendal commented
已建立 https://github.com/openLuat/luatos-soc-rtt @Dozingfiretruck

2021-12-22 15:01 UTC, mysterywolf commented
然后也没有必要一定发布v1.0.0版本
可以把v1.0.0的删掉 根据你的实际需要来

2021-12-22 15:03 UTC, mysterywolf commented on system/LuatOS_SOC/Kconfig
> +       default "v1.0.0"    if PKG_USING_LUATOS_SOC_V100
根据实际需要
不一定非得有

2021-12-22 15:03 UTC, mysterywolf commented on system/LuatOS_SOC/package.json
> +    },
根据实际需要
不一定非得有

2021-12-22 15:03 UTC, mysterywolf commented on system/LuatOS_SOC/Kconfig
> +            bool "v1.0.0"
根据实际需要
不一定非得有

2021-12-22 15:03 UTC, Dozingfiretruck commented
> 然后也没有必要一定发布v1.0.0版本 可以把v1.0.0的删掉 根据你的实际需要来

好的，保留1.0.0是想最近做个初版做1.0.0，所以没删，哈哈

2021-12-22 15:05 UTC, supperthomas commented
> > 然后也没有必要一定发布v1.0.0版本 可以把v1.0.0的删掉 根据你的实际需要来
> 
> 好的，保留1.0.0是想最近做个初版做1.0.0，所以没删，哈哈

可以在readme.md里面简单介绍下这个软件包如何使用，在什么平台，什么开发板下使用

2021-12-22 15:07 UTC, mysterywolf commented
> 可以在readme.md里面简单介绍下这个软件包如何使用，在什么平台，什么开发板下使用

这个应该是在luatos的主仓库里有说明 这个只是专门适配rtt的吧，基本功能应该和luatos是一样的

https://gitee.com/openLuat/LuatOS

2021-12-23 03:27 UTC, Dozingfiretruck commented
> > 可以在readme.md里面简单介绍下这个软件包如何使用，在什么平台，什么开发板下使用
> 
> 这个应该是在luatos的主仓库里有说明 这个只是专门适配rtt的吧，基本功能应该和luatos是一样的
> 
> https://gitee.com/openLuat/LuatOS

仓库已迁移至GitHub

2021-12-23 03:31 UTC, mysterywolf approved these changes

2021-12-24 14:06 UTC, mysterywolf commented on system/LuatOS_SOC/Kconfig
> +    select RT_USING_LIBC
都有什么函数依赖需要这个?

2021-12-24 15:01 UTC, Dozingfiretruck commented on system/LuatOS_SOC/Kconfig
> +    select RT_USING_LIBC
> 都有什么函数依赖需要这个?

luatos需要文件系统下载脚本文件资源等，所以需要RT_USING_DFS ，libc已经不需要了， RT_USING_LIBC以去掉

2021-12-24 19:50 UTC, mysterywolf commented on system/LuatOS_SOC/Kconfig
> +    select RT_USING_LIBC
select DFS_USING_POSIX if RT_VER_NUM >= 0x40100
需要把这句话加上

2021-12-26 08:45 UTC, Dozingfiretruck commented on system/LuatOS_SOC/Kconfig
> +    select RT_USING_LIBC
> 

好的，已经添加，现在使用的是ROMFS，方然其他的也支持，后面会在文档写明

2021-12-27 16:21 UTC, mysterywolf approved these changes

2021-12-28 01:20 UTC, merged