[tinyusb] add HID support
RT-Thread/packages pull request #1148
Opened 2022-01-07 12:37 UTC by tfx2001

2022-01-07 15:56 UTC, mysterywolf requested changes

2022-01-07 15:56 UTC, mysterywolf commented on system/TinyUSB/Kconfig
> +
这个应该给一个default 为 No debug

2022-01-14 17:27 UTC, mysterywolf approved these changes

2022-01-15 03:15 UTC, Guozhanxin approved these changes

2022-01-15 03:15 UTC, merged