[iot][llsync][ble]add the package of llsync
RT-Thread/packages pull request #1178
Opened 2022-02-06 14:20 UTC by supperthomas

添加腾讯的llsync sdk ， 基于nimble的porting。
目前可以控制小灯和进入配网

2022-02-06 16:09 UTC, supperthomas commented
done

2022-02-07 03:39 UTC, mysterywolf requested changes

2022-02-07 03:39 UTC, mysterywolf commented on iot/llsync_sdk_adapter/package.json
> +      "VER_SHA": "fill in latest version branch name, such as master"
master

2022-02-07 04:01 UTC, mysterywolf approved these changes

2022-02-08 04:23 UTC, merged