add simple_xml package
RT-Thread/packages pull request #1206
Opened 2022-03-05 14:09 UTC by xfwangqiang

增加了一款基于C语言的XML解析器的软件包

2022-03-06 01:03 UTC, mysterywolf commented on iot/Kconfig
> -source "$PKGS_DIR/packages/iot/net_server/Kconfig"
为什么删了其他的软件包？这些软件包无效了嘛

2022-03-06 01:04 UTC, mysterywolf commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
这个url有问题的

2022-03-06 01:48 UTC, xfwangqiang commented on iot/Kconfig
> -source "$PKGS_DIR/packages/iot/net_server/Kconfig"
抱歉，这个应该是我操作失误导致的。因为直接在env的packages里面开发的，测试完成后，才发fingerprint这个包一直在变，无法提交，然后重新clone的github上面packages，直接把Iot里的Kconfig和simple_xml文件夹copy过来的，所以在Kconfig中误册了几行。

2022-03-06 01:48 UTC, xfwangqiang commented on iot/Kconfig
> -source "$PKGS_DIR/packages/iot/net_server/Kconfig"
新的提交已经修复了这个问题了

2022-03-06 01:49 UTC, xfwangqiang commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
有个url是有啥问题呢？我测试过好几遍了，都是OK的，是格式问题吗?

2022-03-06 01:56 UTC, mysterywolf commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
https://github.com/RT-Thread/packages/blob/master/iot/agile_telnet/package.json#L31  这种zip格式是正确的

2022-03-06 01:57 UTC, mysterywolf requested changes

2022-03-06 01:57 UTC, mysterywolf commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
换成这个：https://github.com/xfwangqiang/simple_xml/archive/refs/tags/sx-1.1.0.zip

2022-03-06 02:51 UTC, xfwangqiang commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
原来是要使用.zip的格式。软件包开发指南上是说两者都可以，并且给出的示例都是使用的.git，建议是不是把软件包开发指南稍作修改。

2022-03-06 05:30 UTC, mysterywolf commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
@Guozhanxin 郭老师请确认一下，已经发布的版本可以直接写git地址吗？ 还有，这个仓库的tag是“sx-1.1.0”，但是json上写的是“v1.1.0”，是否需要修改。

2022-03-07 04:06 UTC, Guozhanxin commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
是的，我去看看，软件包开发指南去

2022-03-07 04:18 UTC, xfwangqiang commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
url已经修改成.zip了，如果tag的名称必须是v1.1.0，我再去修改

2022-03-07 07:15 UTC, Guozhanxin commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
这到不用，能正常下载就行

2022-03-08 01:15 UTC, xfwangqiang commented on iot/simple_xml/package.json
> +      "URL": "https://github.com/xfwangqiang/simple_xml.git",
@Guozhanxin @mysterywolf 两位大佬，没有问题的话，是不是可以merge这个PR了

2022-03-08 01:26 UTC, mysterywolf commented
+1 @Guozhanxin 郭老师我没啥问题

2022-03-13 13:06 UTC, merged