【添加】cmsis rtos1 软件包索引
RT-Thread/packages pull request #1243
Opened 2022-05-06 05:51 UTC by tyustli

2022-05-06 06:03 UTC, mysterywolf commented
这个软件包可否转移到RT-Thread-package组织上维护

2022-05-06 06:04 UTC, mysterywolf commented
https://github.com/RT-Thread-packages/CMSIS_RTOS1

2022-05-06 18:26 UTC, mysterywolf commented
此处直接按照CMSIS-RTOS2一样 写成最新版本即可 https://github.com/RT-Thread/packages/blob/master/system/CMSIS/CMSIS_RTOS2/Kconfig

2022-05-07 06:43 UTC, mysterywolf approved these changes

2022-05-07 06:55 UTC, mysterywolf requested changes

2022-05-07 06:55 UTC, mysterywolf commented on system/CMSIS/CMSIS_RTOS2/Kconfig
> +        bool "CMSIS RTOS2 compatible CMSIS RTOS1"
compatible with

2022-05-09 01:28 UTC, mysterywolf approved these changes

2022-05-09 01:30 UTC, Guozhanxin approved these changes

2022-05-09 01:31 UTC, merged