[security] Add package libhydrogen
RT-Thread/packages pull request #1245
Opened 2022-05-07 16:11 UTC by wuhanstudio

- 添加密码学软件包 [libhydrogen](https://github.com/jedisct1/libhydrogen)

![image](https://user-images.githubusercontent.com/15157070/167179926-678c7b3b-f908-47a5-a684-6dc46b6aaeeb.gif)

2022-05-07 17:01 UTC, mysterywolf requested changes

2022-05-07 17:01 UTC, mysterywolf commented on security/libhydrogen/Kconfig
> +    select RT_USING_LIBC
这个地方需要注意 LIBC这个宏在4.1.0版本之后已经被干掉了 默认直接可以使用的。

2022-05-07 17:02 UTC, mysterywolf commented on security/libhydrogen/Kconfig
> +    select RT_USING_LIBC
https://github.com/RT-Thread/packages/blob/master/multimedia/vt100/Kconfig#L5

2022-05-07 17:02 UTC, mysterywolf commented on security/libhydrogen/Kconfig
> +    select RT_USING_LIBC
https://github.com/RT-Thread/packages/blob/master/multimedia/termbox/Kconfig#L5-L10

2022-05-07 17:37 UTC, wuhanstudio commented on security/libhydrogen/Kconfig
> +    select RT_USING_LIBC
默认可以用 libc 就很方便了，我改成了

```
select RT_USING_LIBC if RT_VER_NUM < 0x40100
```

2022-05-07 18:23 UTC, mysterywolf approved these changes

2022-05-09 02:25 UTC, Guozhanxin approved these changes

2022-05-09 02:26 UTC, merged