增加 开源物联网平台 IoTSharp 的对接sdk 索引
RT-Thread/packages pull request #1247
Opened 2022-05-08 18:08 UTC by maikebing

适配RT-Thread软件包
支持设备接入 遥测数据上传 属性数据上传
支持物联网网关上传子设备的 遥测数据和 属性数据。 
可以通过配置进行配置服务器等。

2022-05-08 18:11 UTC, mysterywolf requested changes

2022-05-08 18:11 UTC, mysterywolf commented on iot/iot_cloud/iotsharp-c-sdk/package.json
> +  "category": "iot/iot_cloud",
这个位置不能写成iot/iot_cloud吧 @Guozhanxin @aozima

2022-05-08 18:11 UTC, mysterywolf commented on iot/iot_cloud/iotsharp-c-sdk/Kconfig
> +
请删除无意义的多余空行

2022-05-08 18:12 UTC, mysterywolf commented on iot/iot_cloud/iotsharp-c-sdk/package.json
> +    "iotsharp-c-sdk"
如果想增加描述 关键字 可以在此处增加 例如 could之类

2022-05-09 02:13 UTC, maikebing commented on iot/iot_cloud/iotsharp-c-sdk/package.json
> +  "category": "iot/iot_cloud",
我看其他的地方都写这个了。 虽然不知道为啥。

2022-05-09 04:09 UTC, mysterywolf requested changes

2022-05-09 04:09 UTC, mysterywolf commented on iot/iot_cloud/iotsharp-c-sdk/package.json
> +      "URL": "https://github.com/IoTSharp/iotsharp-rtthread-package/archive/v1.0.0.zip",
这个地址有问题改成：
https://github.com/IoTSharp/iotsharp-rtthread-package/archive/refs/tags/1.0.0.zip

2022-05-09 10:15 UTC, Guozhanxin commented
![image](https://user-images.githubusercontent.com/25633294/167389962-35d74a5e-4381-442c-94ea-639a5b6c21ba.png)
kconfig 文件写的有问题

2022-05-09 12:53 UTC, maikebing commented
这个有什么校验工具吗 ？
我发现我这pr改的次数也太多了。 这让我有点慌。

2022-05-09 15:10 UTC, mysterywolf commented
commit次数不用担心 你提交100次也没有关系 我们最后合并的时候会压缩成一个commit😄

2022-05-09 15:16 UTC, maikebing commented
最后一个的ci没出来。 不知道过不过的去。

2022-05-10 02:17 UTC, Guozhanxin commented
> 这个有什么校验工具吗 ？ 我发现我这pr改的次数也太多了。 这让我有点慌。

可以本地输入menuconfig测试下的吧

2022-05-10 02:51 UTC, maikebing commented
感谢 @Guozhanxin

2022-05-10 03:08 UTC, maikebing commented
终于通过了。

2022-05-10 03:33 UTC, merged