添加一个IO输入滤波软件包
RT-Thread/packages pull request #1299
Opened 2022-07-11 08:57 UTC by lizdDong

2022-07-13 02:43 UTC, mysterywolf requested changes

2022-07-13 02:43 UTC, mysterywolf commented on peripherals/io_input_filter/package.json
> +      "URL": "https://io_input_filter-1.0.0.zip",
```suggestion
      "URL": "https://github.com/lizdDong/io_input_filter/archive/refs/tags/v1.0.0.zip",
    
```

2022-07-18 08:55 UTC, Guozhanxin commented
这个还需要在上级目录加一个 引用。
https://github.com/RT-Thread/packages/blob/d52a4d096be20b0ee8bec4b173afc3aeaf5b8d0a/peripherals/Kconfig

2022-07-20 20:09 UTC, mysterywolf commented
@Guozhanxin 郭老师请重启一下ci流程

2022-07-22 02:30 UTC, mysterywolf approved these changes

2022-07-22 03:42 UTC, merged