[lvgl] using explicit version choice instead of hidden options
RT-Thread/packages pull request #1300
Opened 2022-07-12 07:34 UTC by luhuadong

BSP 包 nuvoton/nk-n9h30 添加 LVGL 软件包后，默认配置编译不通过，原因是部分源文件使用了 `LV_VERSION_CHECK` 宏检查版本是否为 v8.2.0，但是默认拉取的却是 latest 版本（已经到 v9.0 了）。

```c
#if LV_USE_GPU_N9H30_GE2D && LV_VERSION_CHECK(8, 2, 0)
```

这个 Bug 是在使用 NuMaker-HMI-N9H30 开发板的时候发现的，我不确定其他 BSP 包是否有类似的问题，但我认为显式地让用户决定 LVGL 的版本更合理。对于有特殊需求的 BSP 或者工具，例如 NXP GUIGuider，应该在其对应的 BSP、软件包、说明文档中进行适配或者给出提示，而不是在 Kconfig 中隐式处理。否则会给 LVGL 的开发者和相关软件包管理者带来不必要的麻烦。

2022-07-12 15:45 UTC, mysterywolf requested changes

2022-07-12 15:46 UTC, mysterywolf requested changes

2022-07-12 15:46 UTC, mysterywolf commented on multimedia/LVGL/LVGL/Kconfig
> -    config PKG_LVGL_VER_NUM
PKG_LVGL_VER_NUM 不能删除，这个其他软件包依赖

2022-07-12 18:34 UTC, mysterywolf commented on multimedia/LVGL/LVGL/Kconfig
> -    config PKG_LVGL_VER_NUM
不可以这么改，PKG_LVGL_VER_NUM 可以做到在一定范围内的版本的判断，比如某个功能，只有大于8.3.0版本才能使能，通过PKG_LVGL_USING_V08020 这种宏实现起来就非常麻烦

2022-07-13 00:35 UTC, luhuadong commented on multimedia/LVGL/LVGL/Kconfig
> -    config PKG_LVGL_VER_NUM
那看一下怎么改，既能保留 PKG_LVGL_VER_NUM，又能让用户选择 LVGL 的版本？

2022-07-13 02:20 UTC, luhuadong commented
> #1301 我改了一下 这里 看看可不可以

可以，测试过没问题

2022-07-13 02:42 UTC, mysterywolf commented
OK 那这个PR我就先关了

2022-07-13 02:42 UTC, closed without merging