[arduino][adafruit] 增加SHT31-D驱动库
RT-Thread/packages pull request #1342
Opened 2022-09-21 14:04 UTC by Yaochenger

[arduino][adafruit] 增加SHT31-D驱动库

2022-09-21 14:05 UTC, Yaochenger commented
Start

2022-09-21 15:15 UTC, mysterywolf requested changes

2022-09-21 15:15 UTC, mysterywolf commented on arduino/sensors/Adafruit_SHT31/Kconfig
> +        default "/packages/arduino/sensors/Adafruit_SHT31"
这个位置不需要改，自动生成是什么就是什么就可以，CI报错就是因为这里

2022-09-21 15:16 UTC, mysterywolf commented
不是这里的问题 我再看一下

2022-09-21 17:06 UTC, mysterywolf requested changes

2022-09-21 17:06 UTC, mysterywolf commented on arduino/sensors/Kconfig
> +source "$PKGS_DIR/packages/arduino/sensors/Adafruit-SHT31-D/Kconfig"
这个名字有问题，你的文件夹叫Adafruit-SHT31结果这里的路径写成了Adafruit-SHT31-D，严格按照文件夹的名字来。改为：
```suggestion
source "$PKGS_DIR/packages/arduino/sensors/Adafruit-SHT31/Kconfig"
```

2022-09-21 17:06 UTC, mysterywolf commented on arduino/sensors/Adafruit_SHT31/Kconfig
> +    bool "Adafruit SHT31-D: Temperature and Humidity Sensor library"
不用强调-D 驱动都是通用的，把这里边含有-D的都删了就行

2022-09-22 02:00 UTC, mysterywolf commented
你的软件包名字注册错了 Adafruit-SHT31 不是Adafruit_SHT31 （虽然官方仓库上用下划线，但是为了方面用户看见，我们这里都是统一用的横线/减号而非下划线）

2022-09-22 02:05 UTC, mysterywolf commented
建议你重新提交一个PR。第一项问你软件包的名字，需要填入：Adafruit-SHT31。而非下划线。

2022-09-22 02:11 UTC, closed without merging