[arduino][adafruit] 增加ICM20X驱动库
RT-Thread/packages pull request #1343
Opened 2022-09-21 14:07 UTC by kurisaW

2022-09-21 14:22 UTC, kurisaW reviewed
[modify] 修改BSD License

2022-09-21 17:04 UTC, mysterywolf requested changes
非常棒！细节上按照给出的建议修改好即可

2022-09-21 17:04 UTC, mysterywolf commented on arduino/sensors/Adafruit-ICM20X/package.json
> +  "description_zh": "这是Adafruit ICM2eX Arduino库,可与TDK Invensense ICM20649和ICM20948运动传感器一起使用",
```suggestion
  "description_zh": "TDK Invensense ICM20649和ICM20948 IMU运动传感器Arduino库",
```

2022-09-21 17:04 UTC, mysterywolf commented on arduino/sensors/Adafruit-ICM20X/Kconfig
> +    bool "Adafruit ICM20X:This is the Adafruit ICM20X Arduino Library for use with the TDK Invensense ICM20649 and ICM20948 motion sensors"
```suggestion
    bool "Adafruit ICM20X: TDK Invensense ICM20649 and ICM20948 motion sensors"
```

2022-09-21 17:04 UTC, mysterywolf commented on arduino/sensors/Adafruit-ICM20X/Kconfig
> +    bool "Adafruit ICM20X:This is the Adafruit ICM20X Arduino Library for use with the TDK Invensense ICM20649 and ICM20948 motion sensors"
Kconfig的描述要稍微精炼一些，因为太长了在menuconfig里显示不全

2022-09-21 17:04 UTC, mysterywolf commented on arduino/sensors/Adafruit-ICM20X/package.json
> +  "description_zh": "这是Adafruit ICM2eX Arduino库,可与TDK Invensense ICM20649和ICM20948运动传感器一起使用",
翻译的稍微通顺一些，这个汉语表达不是正常中国人说的话😂

2022-09-21 17:04 UTC, mysterywolf commented on arduino/sensors/Adafruit-ICM20X/package.json
> +    "motion"
```suggestion
    "ICM20649",
    "ICM20948",
    "motion"
```

2022-09-22 00:30 UTC, kurisaW commented on arduino/sensors/Adafruit-ICM20X/package.json
> +  "description_zh": "这是Adafruit ICM2eX Arduino库,可与TDK Invensense ICM20649和ICM20948运动传感器一起使用",
😅 好的好的，已修改

2022-09-22 00:32 UTC, kurisaW commented on arduino/sensors/Adafruit-ICM20X/Kconfig
> +    bool "Adafruit ICM20X:This is the Adafruit ICM20X Arduino Library for use with the TDK Invensense ICM20649 and ICM20948 motion sensors"
这个Kconfig里的描述在menuconfig中最多能支持多少字节啊，我下次注意精炼点

2022-09-22 01:35 UTC, merged