[arduino][seeed] 添加adxl335驱动库
RT-Thread/packages pull request #1492
Opened 2022-10-29 14:58 UTC by Z8MAN8

2022-10-29 15:15 UTC, mysterywolf requested changes

2022-10-29 15:15 UTC, mysterywolf commented on arduino/sensors/Seeed-ADXL335/package.json
> +  "description_zh": "Seeed-ADXL335三轴加速度计驱动",
描述的时候没有横杠 Seeed ADXL335

2022-10-29 15:15 UTC, mysterywolf commented on arduino/sensors/Seeed-ADXL335/package.json
> +  "description_zh": "Seeed-ADXL335三轴加速度计驱动",
只有软件包名字带横杠

2022-10-30 00:01 UTC, Z8MAN8 commented on arduino/sensors/Seeed-ADXL335/package.json
> +  "description_zh": "Seeed-ADXL335三轴加速度计驱动",
已修改

2022-10-30 00:34 UTC, merged