添加了Adafruit-VL53L1X软件包
RT-Thread/packages pull request #1535
Opened 2022-11-29 09:13 UTC by linshire

2022-12-01 05:41 UTC, mysterywolf requested changes

2022-12-01 05:41 UTC, mysterywolf commented on arduino/sensors/Adafruit-VL53L1X/Kconfig
> +       default "v1.0.0"    if PKG_USING_ARDUINO_ADAFRUIT_VL53L1X_V100
1.0版本需要删除掉，直接保持latest版本即可

2022-12-01 05:41 UTC, mysterywolf commented on arduino/sensors/Adafruit-VL53L1X/Kconfig
> +    bool "Please add description of Adafruit-VL53L1X in English."
描述

2022-12-01 05:41 UTC, mysterywolf commented on arduino/sensors/Adafruit-VL53L1X/package.json
> +  "description": "Please add description of Adafruit-VL53L1X in English.",
描述

2022-12-01 05:44 UTC, mysterywolf requested changes

2022-12-01 05:44 UTC, mysterywolf commented on arduino/sensors/Adafruit-VL53L1X/Kconfig
> +    default n
缺少依赖

2022-12-07 05:10 UTC, linshire commented on arduino/sensors/Adafruit-VL53L1X/Kconfig
> +    default n
g

2022-12-07 15:58 UTC, closed without merging