add spi-tools.
RT-Thread/packages pull request #1612
Opened 2023-05-04 16:21 UTC by Vandoul

新增spi-tools包

2023-05-05 01:24 UTC, supperthomas commented
這個spi名字是不是有些通用了？建議改成spitool，是不是不太容易和別人衝突？

2023-05-05 01:46 UTC, Vandoul commented
嗯嗯，晚上再改一下提交

2023-05-05 01:47 UTC, supperthomas approved these changes

2023-05-05 09:20 UTC, supperthomas commented
https://github.com/RT-Thread/packages/actions/runs/4884959799?pr=1612
请看下这个错误：
https://github.com/RT-Thread/packages/suites/12679130054/artifacts/681136385

2023-05-05 09:20 UTC, supperthomas commented
![image](https://user-images.githubusercontent.com/60349489/236421366-1ffdc9cb-6fb7-4551-914c-1b80dbcf065b.png)

2023-05-08 01:29 UTC, supperthomas commented
@mysterywolf

2023-05-08 01:29 UTC, supperthomas approved these changes

2023-05-08 01:31 UTC, mysterywolf requested changes

2023-05-08 01:31 UTC, mysterywolf commented on peripherals/Kconfig
> +source "$PKGS_DIR/packages/peripherals/spi-tools/Kconfig"
把版本判断放在这一级吧
```suggestion
if RT_VER_NUM > 0x40101
source "$PKGS_DIR/packages/peripherals/spi-tools/Kconfig"
endif
```

2023-05-08 01:32 UTC, mysterywolf requested changes

2023-05-08 01:32 UTC, mysterywolf commented on peripherals/spi-tools/Kconfig
> +if RT_VER_NUM > 0x40101
```suggestion
```

2023-05-08 01:32 UTC, mysterywolf commented on peripherals/spi-tools/Kconfig
> +endif
```suggestion
```

2023-05-08 02:40 UTC, mysterywolf approved these changes

2023-05-09 02:39 UTC, merged