qkey release v1.12
RT-Thread/packages pull request #1621
Opened 2023-06-01 06:01 UTC by qiyongzhong0

qkey release v1.12 and quick_led release v1.02

2023-06-01 10:54 UTC, supperthomas commented
https://github.com/RT-Thread/packages/suites/13297090873/artifacts/725956049

2023-06-01 16:54 UTC, mysterywolf approved these changes

2023-06-02 03:39 UTC, mysterywolf commented
pid的软件包分类请调整为signalprocess分类下

2023-06-02 03:56 UTC, mysterywolf requested changes

2023-06-02 03:56 UTC, mysterywolf commented on signalprocess/qpid/package.json
> +    "PID"，
中文逗号

2023-06-02 03:56 UTC, mysterywolf commented on signalprocess/qpid/package.json
> +  "category": "misc",
分类错了

2023-06-02 03:56 UTC, mysterywolf commented on signalprocess/qpid/package.json
> +  "description": "A quick and easy-to-use PID automatic control algorithm package, that supports incremental and positional algorithms..",
```suggestion
  "description": "A quick and easy-to-use PID automatic control algorithm package, that supports incremental and positional algorithms.",
```

2023-06-02 04:33 UTC, mysterywolf approved these changes

2023-06-02 04:34 UTC, merged