更新软件滤波模块API，使其更加方便易用
RT-Thread/packages pull request #1639
Opened 2023-07-23 07:53 UTC by lizdDong

IO输入软件滤波模块升级至2.0.0，API更新，更加方便使用

2023-07-23 10:05 UTC, vacabun commented
软件包测试是v1.0.0版本没通过。

![2d941396472bd36ab428eae1c0bac3fa](https://github.com/RT-Thread/packages/assets/34151213/3cfced33-9edb-42c3-9328-32e145374751)

可以先合并。

2023-07-24 02:24 UTC, supperthomas requested changes

2023-07-24 02:24 UTC, supperthomas commented on peripherals/io_input_filter/Kconfig
> +        int "滤波次数"
Kconfig中有中文的话，有些用户可能会用起来比较困难。

2023-07-24 05:56 UTC, supperthomas approved these changes

2023-07-26 09:04 UTC, merged