add configure of iperf stack size
RT-Thread/packages pull request #1730
Opened 2024-04-18 08:15 UTC by zmshahaha

2024-04-18 22:20 UTC, mysterywolf requested changes

2024-04-18 22:20 UTC, mysterywolf commented on iot/netutils/Kconfig
> +
```suggestion
    config IPERF_THREAD_STACK_SIZE
        int "the stack size of iperf thread"
        depends on PKG_NETUTILS_IPERF
        range 2048 65536
        default aarch64下的值 if ARCH_CPU_64BIT
        default 2048

```

2024-04-19 01:23 UTC, zmshahaha commented on iot/netutils/Kconfig
> +
已按照该方式修改

2024-04-19 01:45 UTC, mysterywolf approved these changes

2024-04-19 01:46 UTC, merged