squline studio selects macros for each lvgl version
RT-Thread/packages pull request #1749
Opened 2024-07-02 11:06 UTC by kurisaW

2024-07-02 13:11 UTC, Rbb666 approved these changes

2024-07-02 15:04 UTC, mysterywolf approved these changes

2024-07-02 15:05 UTC, mysterywolf requested changes

2024-07-02 15:05 UTC, mysterywolf commented on multimedia/LVGL/LVGL/Kconfig
> +    endchoice
这段写的啥意思？

2024-07-03 01:20 UTC, kurisaW commented on multimedia/LVGL/LVGL/Kconfig
> +    endchoice
现在的lvgl在squaline studio中依赖项有两个版本：

1.最新的master版本是使用的`PKG_LVGL_USING_SQUARELINE`依赖项
2.其余低版本使用的则是`PKG_USING_LVGL_SQUARELINE`依赖项

这两个依赖项没统一，如果想要使用最新的这个定义而且不修改lvgl主仓修改packages的Kconfig是最方便的，要不就是将lvgl主仓的master版本中有关squaline studio的依赖项换回`PKG_USING_LVGL_SQUARELINE`

2024-07-04 02:12 UTC, merged