[sensor_v1] ina226 pkg adapt sensor_v1 frame
RT-Thread/packages pull request #1780
Opened 2024-09-10 02:52 UTC by CYFS3

2024-09-23 01:56 UTC, kurisaW commented
@Rbb666 @mysterywolf 该PR已通过审核，可以合并

2024-09-23 22:24 UTC, mysterywolf requested changes

2024-09-23 22:24 UTC, mysterywolf commented on peripherals/sensors/ina226/Kconfig
> +		select PKG_INA226_USING_SENSOR_V1
这里应该是空格 不应该是tab

2024-09-24 04:38 UTC, CYFS3 commented on peripherals/sensors/ina226/Kconfig
> +		select PKG_INA226_USING_SENSOR_V1
已修改

2024-09-26 01:05 UTC, mysterywolf approved these changes

2024-09-26 01:05 UTC, merged