增加 GT917S 软件包
RT-Thread/packages pull request #825
Opened 2020-12-30 06:20 UTC by lilisheng411527

2020-12-30 06:56 UTC, Guozhanxin commented
最好基于最新的master重新提交commit

2020-12-30 07:52 UTC, armink commented
请注意代码格式，并统一修改为 GitHub 的链接地址

2020-12-30 09:32 UTC, lilisheng411527 commented
添加  GT917S 软件包

2020-12-30 09:42 UTC, armink commented on peripherals/touch/Kconfig
> +	    source "$PKGS_DIR/packages/peripherals/touch/ft6206/Kconfig"
这里为啥多复制一条？

2020-12-30 09:42 UTC, armink commented on peripherals/touch/Kconfig
> +	    source "$PKGS_DIR/packages/peripherals/touch/gt917s/Kconfig"
注意格式，tab 转 空格

2020-12-30 09:42 UTC, armink commented on peripherals/touch/gt917s/package.json
> +      "URL": "https://github.com/lilisheng411527/gt917s.git",
发布版本，请在 GitHub 上发布，并使用zip链接

2021-01-01 04:00 UTC, armink requested changes

2021-01-01 04:00 UTC, armink commented on peripherals/touch/gt917s/package.json
> +      "URL": "https://github.com/lilisheng411527/gt917s.git",
```suggestion
      "URL": "https://github.com/lilisheng411527/gt917s/archive/v1.0.0.zip",
```

2021-01-04 02:06 UTC, lilisheng411527 commented
增加 GT917S 软件包

2021-01-05 04:40 UTC, armink commented on peripherals/touch/gt917s/package.json
> +    {
latest 的保留，别删除了

2021-01-05 07:25 UTC, lilisheng411527 commented
微调

2021-01-05 09:22 UTC, merged